name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check syntax
        run: perl -c zzclone
      - name: Run regression tests
        run: prove -v t/
